# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: payment.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'payment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpayment.proto\x12\x08payments\" \n\x0ePaymentRequest\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x01\"4\n\x0fPaymentResponse\x12\x10\n\x08\x61pproved\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2W\n\x0ePaymentService\x12\x45\n\x0eProcessPayment\x12\x18.payments.PaymentRequest\x1a\x19.payments.PaymentResponseB\x1d\n\x19\x62r.com.ecommerce.paymentsP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\031br.com.ecommerce.paymentsP\001'
  _globals['_PAYMENTREQUEST']._serialized_start=27
  _globals['_PAYMENTREQUEST']._serialized_end=59
  _globals['_PAYMENTRESPONSE']._serialized_start=61
  _globals['_PAYMENTRESPONSE']._serialized_end=113
  _globals['_PAYMENTSERVICE']._serialized_start=115
  _globals['_PAYMENTSERVICE']._serialized_end=202
# @@protoc_insertion_point(module_scope)
